List<questions> comQuestions = [
  questions(
      question: "Which is the largest commercial Bank of India",
      a: "PNB",
      b: "SBI",
      c: "UCO",
      d: "BOB",
      answer: "SBI"),
  questions(
      question: "Full form of YONO",
      a: "You only need one",
      b: "You only new one",
      c: "You observe new one",
      d: "You observe need one",
      answer: "You only need one")
];
List<questions> normalQuestions = [
  questions(
      question: "Who was the first Governor of the Reserve Bank of India?",
      a: "Osborne A Smith",
      b: "Robert Aitken",
      c: "William Lamond",
      d: "C D Deshmukh",
      answer: "Osborne A Smith"),
  questions(
      question: "When was the Reserve Bank of India nationalised",
      a: "1-Jan-35",
      b: "1-Apr-35",
      c: "1-Jan-49",
      d: "1-Jan-49",
      answer: "1-Jan-49"),
  questions(
      question: "At which place does the Hooghly river enters in Bengal?",
      a: "Maldah",
      b: "Farakka",
      c: "Murshidabad",
      d: "Hugli",
      answer: "Murshidabad"),
  questions(
      question: "Who is the founder of Brahmo Samaj?",
      a: "Rajaram Mohan Roy",
      b: "Dadabhai Naroji",
      c: "Aurbindo",
      d: "Suryasen",
      answer: "Rajaram Mohan Roy"),
  questions(
      question:
          "Which social reformer of Bengal worked tirelessly for widow marriage, primarily?",
      a: "Rajaram Mohan Roy",
      b: "Ishwarchand Vidyasagar",
      c: "Vivekanand",
      d: "kamini Devi",
      answer: "IshwarChand Vidyasagar"),
  questions(
      question: "Where did the famous social reformer Raja Ram Mohan Roy die?",
      a: "Kolkata",
      b: "London",
      c: "Paris",
      d: "Delhi",
      answer: "London"),
  questions(
      question: "Who wrote 'New Lamps for Old?",
      a: "Rajaram Mohan Roy",
      b: "Dadabhai Naroji",
      c: "Aurbindo",
      d: "Suryasen",
      answer: "Aurbindo"),
  questions(
      question: "Who is associated with the concept of 'Navvedanta'?",
      a: "Rajaram Mohan Roy",
      b: "Ishwarchand Vidyasagar",
      c: "Vivekanand",
      d: "Lala Lajpat Rai",
      answer: "Vivekanand"),
  questions(
      question: "Who started the Kirtan in Bhakti Movement?",
      a: "Vivekanand",
      b: "Chaitanya Mahaprabhu",
      c: "Aurbindo",
      d: "Gopla Krishan Gokhale",
      answer: "Chaitanya Mahaprabhu"),
  questions(
      question: "When was  founder of VISHWA BHARTI ?",
      a: "Gopal Krishan Gokhale",
      b: "Dadabhai Naroji",
      c: "Bal Gangadhar Tilak",
      d: "Ravindranath Tagore",
      answer: "Ravindranath Tagore"),
  questions(
      question: "When was founder of Ramakrishna Mission ?",
      a: "Rajaram Mohan Roy",
      b: "Ishwarchand Vidyasagar",
      c: "Vivekanand",
      d: "Lala Lajpat Rai",
      answer: "1897"),
  questions(
      question: "Founder of Kolkata",
      a: "Wellesely",
      b: "job charnock",
      c: "Curzon",
      d: "Lyton",
      answer: "job charnock"),
  questions(
      question: "Digha Sea Beach in which District?",
      a: "Dakshin Medinipur",
      b: "Purba Medinipur",
      c: "Paschim Medinipur",
      d: "Uttar Medinipur",
      answer: "Purba Medinipur"),
  questions(
      question: "The world's most treacherous river",
      a: "Ganga",
      b: "Hugli",
      c: "Yamuna",
      d: "Saraswati",
      answer: "Hughli"),
  questions(
      question: "Who is the father of Nation?",
      a: "Gurudev",
      b: "Satyendra Bose",
      c: "Mahatma Gandhi",
      d: "Rajaram Mohan Roy",
      answer: "Mahatma Gandhi"),
  questions(
      question: "Who is the first President of India?",
      a: "Rajendra Prasad",
      b: "APJ Abdul Kalam",
      c: "Droupadi Murmu",
      d: "Ram Nath Kovind",
      answer: "Rajendra Prasad"),
  questions(
      question: "Where was Singalia National Park is ",
      a: "Siliguri",
      b: "Darjeeling",
      c: "Nepal",
      d: "Murshidabad",
      answer: "Darjeeling"),
  questions(
      question: "Toto' tribal in which state",
      a: "Tamilnadu",
      b: "Andhra Pradesh",
      c: "West Bengal",
      d: "Jharkhand",
      answer: "West Bengal"),
  questions(
      question: "Who is known as Father of Indian constitution",
      a: "Sardar vallabhbhai Patel",
      b: "Dr Rajendra Prasad",
      c: "Mahatma Gandhi",
      d: "Dr B R Ambedkar",
      answer: "Dr B R Ambedkar"),
  questions(
      question: "Metro Rail is started in Kolkata",
      a: "1984",
      b: "1986",
      c: "1988",
      d: "1989",
      answer: "1984"),
  questions(
      question: "Who was the first Prime Minister of India?",
      a: "Gopal Krishan Gokhale",
      b: "Jawaharlal Nehru",
      c: "Bal Gangadhar Tilak",
      d: "Ravindranath Tagore",
      answer: "Jawaharlal Nehru"),
  questions(
      question: "Known as-'Doors towards Bhutan'",
      a: "Siliguri",
      b: "Banarhat",
      c: "Darjiling",
      d: "Jalpaiguri",
      answer: "Jalpaiguri"),
  questions(
      question: "Which one is of the highest length",
      a: "Teesta",
      b: "Mahananda",
      c: "Jaldhaka",
      d: "Jalangai",
      answer: "Teesta"),
  questions(
      question: "India lies in which continent?",
      a: "Africa",
      b: "Antarctica",
      c: "Asia",
      d: "North America",
      answer: "Asia"),
  questions(
      question: "How many Cricket world cup does India have?",
      a: "4",
      b: "3",
      c: "2",
      d: "1",
      answer: "2"),
  questions(
      question: "'CANADA DAM' is associated with which project",
      a: "Mayurakshi",
      b: "Damodar",
      c: "Kansabati",
      d: "Jaldhaka",
      answer: "Mayurakshi"),
  questions(
      question: "First Jute mill in India",
      a: "Naihati",
      b: "Serampore",
      c: "Kulti",
      d: "Rishra",
      answer: "Rishra"),
  questions(
      question: "Durgapur Steel Plant was set up in collaboration with:",
      a: "Russia",
      b: "Germany",
      c: "Britain",
      d: "France",
      answer: "Britain"),
  questions(
      question: "Smallest State in India?",
      a: "Sikkim",
      b: "Goa",
      c: "UP",
      d: "MP",
      answer: "Goa"),
  questions(
      question: "Who was the inspiration behind'YOUNG BANGAL MOVEMENT'",
      a: "Madhusudan Datta",
      b: "Derozio",
      c: "Ramgopal ghosh",
      d: "Rammohan Roy",
      answer: "Derozio"),
  questions(
      question: "National Tree of India ?",
      a: "Pipal",
      b: "Banyan",
      c: "Banana",
      d: "Teak",
      answer: "Banyan"),
  questions(
      question: "Akbar of Bangal",
      a: "Pratapaditya",
      b: "Ilyaas Shah",
      c: "Sirajuddaula",
      d: "Hussain Shah",
      answer: "Hussain Sah"),
  questions(
      question: "Ashutosh is another name of ",
      a: "Shiv",
      b: "Ganga",
      c: "Vishnu",
      d: "Ganesh",
      answer: "Shiv"),
  questions(
      question: "Vishnupur Mela in which district",
      a: "Harimohanpur",
      b: "Darjiling",
      c: "Bolpur",
      d: "Bankura",
      answer: "Bankura"),
  questions(
      question: "Who has given the name 'MAHATMA' to Gandhi",
      a: "Rajaram Mohan Roy",
      b: "Ishwarchand Vidyasagar",
      c: "Vivekanand",
      d: "Ravindranath Thakur",
      answer: "Ravindranath Thakur"),
  questions(
      question: "Kolkata is the first city to have a ______",
      a: "Metro",
      b: "Bus",
      c: "Tram ",
      d: "All of these ",
      answer: "Metro"),
  questions(
      question: "In West Bengal, the first railway station was erected at",
      a: "Chandan nagar",
      b: "Howrah Railway Junction Station",
      c: "Chinsurah",
      d: "Sealdah",
      answer: "Howrah Railway Junction Station"),
  questions(
      question: "Which country’s size is equivalent to West Bengal’s?",
      a: "Serbia ",
      b: "Australia ",
      c: "NewZee Land",
      d: "Srilanka ",
      answer: "Srilanka "),
  questions(
      question:
          "After West Bengal became an Indian state, who was the first Chief Minister of the state?",
      a: "Siddhartha Shankar Ray",
      b: "Prafulla Chandra Sen",
      c: "Ajoy Mukherjee",
      d: "Bidhan Chandra Roy",
      answer: "Bidhan Chandra Roy"),
  questions(
      question:
          "What is West Bengal’s position on India’s list of largest states by area?",
      a: "14th ",
      b: "13th ",
      c: "15th ",
      d: "16th ",
      answer: "14th "),
  questions(
      question: "What is the most sensitive organ of our body?",
      a: "Skin",
      b: "Eye",
      c: "Nose",
      d: "Ear",
      answer: "Skin"),
  questions(
      question: "Giddha is the folk dance of",
      a: "Uttar Pradesh",
      b: "Punjab",
      c: "Jharkhand",
      d: "Odisha",
      answer: "Punjab"),
  questions(
      question: "Who invented computer?",
      a: "Sundar Pichai",
      b: "Bill Gates",
      c: "Satya Nadella",
      d: "Charles Babbage",
      answer: "Charles Babbage"),
  questions(
      question: "How many dots appears on a pair of dice?",
      a: "21",
      b: "42",
      c: "36",
      d: "54",
      answer: "42"),
  questions(
      question: "What is the only body part that is fully grown from birth?",
      a: "Eyeball",
      b: "Skin",
      c: "Eye",
      d: "Nose",
      answer: "Eyeball"),
  questions(
      question: "In which country was Elon Musk born?",
      a: "America",
      b: "UK",
      c: "South Africa",
      d: "Canada",
      answer: "South Africa"),
  questions(
      question: "Who is the host of KBC?",
      a: "Amitabh Bachchan",
      b: "Amir Khan",
      c: "Shahrukh Khan",
      d: "Virat Kohli",
      answer: "Amitabh Bachchan"),
  questions(
      question: "Who is the first Indian to win a Nobel prize?",
      a: "Jagadish Ch. Bose",
      b: "Rabindranath Tagore",
      c: "Amartya Sen",
      d: "Mother Teresa",
      answer: "Rabindranath Tagore"),
  questions(
      question: "Who heads RBI?",
      a: "Dinesh Khara",
      b: "Shaktikanta Das",
      c: "Raghuram Rajan",
      d: "Urijit Patel",
      answer: "Shaktikanta Das"),
  questions(
      question: "Durand cup is associated with which game?",
      a: "Hockey",
      b: "Cricket",
      c: "Football",
      d: "Basketball",
      answer: "Football"),
  questions(
      question: "Present brand ambassador of SBI?",
      a: "M S Dhoni",
      b: "Virat Kohli",
      c: "Amitabh Bachhan",
      d: "Shah Rukh Khan",
      answer: "M S Dhoni"),
  questions(
      question: "Hemis National Park is located at",
      a: "Jammu & Kashmir",
      b: "Uttarakhand",
      c: "Rajasthan",
      d: "Himachal Pradesh",
      answer: "Jammu & Kashmir"),
  questions(
      question: "Kolkata international Book Fair Started in which year?",
      a: "1975",
      b: "1976",
      c: "1977",
      d: "1978",
      answer: "1976"),
  questions(
      question: "International women’s day",
      a: "8 January",
      b: "8 February",
      c: "8 March",
      d: "9 March",
      answer: "8 March"),
  questions(
      question: "Biggest waterfall in India located in which state?",
      a: "Karnataka",
      b: "Tamilnadu",
      c: "Kerala",
      d: "Shillong",
      answer: "Karnataka"),
  questions(
      question: "Largest river Basin in India ",
      a: "Godavari",
      b: "Ganga",
      c: "Mahanadi",
      d: "Sutlej",
      answer: "Ganga"),
  questions(
      question: "Bhitarkanika national park is located at which state?",
      a: "Odisha",
      b: "West Bengal",
      c: "Jharkhand",
      d: "Bihar",
      answer: "Odisha"),
  questions(
      question: "Bangladesh was formed in which year?",
      a: "1973",
      b: "1972",
      c: "1970",
      d: "1971",
      answer: "1971"),
  questions(
      question: "Who is the Grand old man of India?",
      a: "Dadabhai Naoroji",
      b: "Jawaharlal Nehru",
      c: "Sardar Ballav Bhai Patel",
      d: "Mahatma Gandhi",
      answer: "Dadabhai Naoroji"),
  questions(
      question:
          "In which Indian State is Chauri Chaura village is located in state?",
      a: "Bihar",
      b: "Odisha",
      c: "Uttar Pradesh",
      d: "Jharkhand",
      answer: "Uttar Pradesh"),
];

class questions {
  String? question;
  String? a;
  String? b;
  String? c;
  String? d;
  String? answer;
  questions({this.question, this.a, this.b, this.c, this.d, this.answer});
}
